"""
beam_search/planner.py — Production Beam Search CAD Planner
=============================================================
Implements a real incremental beam search over construction sequences.

Instead of simply scoring a flat list of candidates, this planner:

1. Starts from an empty construction graph
2. At each step, expands the top-K partial plans by one operation
3. Scores each expansion using the multi-dimensional PlanScorer
4. Prunes to keep only the top beam_width candidates
5. Records the full PlanningTrace for explainability

Integration with shared-schemas:
  - Emits PlanningTrace with BeamCandidate, ScoringBreakdown
  - Records rejected plans with reasons
  - Logs ambiguity resolutions from the resolver
"""
from __future__ import annotations

import logging
import time
from typing import Any, Dict, List, Optional, Tuple

from construction.graph import ConstructionGraph, ConstructionNode
from evaluation.scorer import PlanScorer, ScoringBreakdown

logger = logging.getLogger("cad_planner.beam_search.planner")


class BeamCandidate:
    """A candidate plan tracked during beam search."""

    def __init__(
        self,
        graph: ConstructionGraph,
        score: float = 0.0,
        breakdown: Optional[ScoringBreakdown] = None,
        history: Optional[List[str]] = None,
    ) -> None:
        self.graph = graph
        self.score = score
        self.breakdown = breakdown or ScoringBreakdown()
        self.history = history or []

    def clone(self) -> "BeamCandidate":
        return BeamCandidate(
            graph=self.graph.clone(),
            score=self.score,
            breakdown=self.breakdown,
            history=list(self.history),
        )


class BeamSearchPlanner:
    """
    Beam search planner that explores multiple construction strategies.

    The planner operates in two modes:
      1. **Full beam search** — incrementally builds construction graphs
         step-by-step, pruning at each level (used when GGL has ambiguity)
      2. **Candidate ranking** — scores pre-built candidate graphs and
         selects the best (used when candidates are pre-generated by
         the ambiguity resolver)

    Both modes record a complete PlanningTrace for explainability.
    """

    def __init__(
        self,
        beam_width: int = 3,
        max_depth: int = 50,
        scorer: Optional[PlanScorer] = None,
    ) -> None:
        self.beam_width = beam_width
        self.max_depth = max_depth
        self.scorer = scorer or PlanScorer()

    def plan(self, candidates: List[ConstructionGraph]) -> ConstructionGraph:
        """
        Evaluate candidate construction graphs and return the best.

        This is the backward-compatible API. For full trace output,
        use plan_with_trace() instead.

        Args:
            candidates: Pre-built construction graph alternatives.

        Returns:
            The highest-scoring ConstructionGraph.

        Raises:
            ValueError: If no candidates are provided.
        """
        best, _ = self.plan_with_trace(candidates)
        return best

    def plan_with_trace(
        self, candidates: List[ConstructionGraph]
    ) -> Tuple[ConstructionGraph, Dict[str, Any]]:
        """
        Evaluate candidates and return both the best graph and the
        full PlanningTrace as a dict.

        Args:
            candidates: Pre-built construction graph alternatives.

        Returns:
            Tuple of (best_graph, planning_trace_dict).
        """
        if not candidates:
            raise ValueError("No candidates provided to Beam Search Planner")

        t0 = time.monotonic()

        # Score all candidates
        scored: List[BeamCandidate] = []
        for idx, cg in enumerate(candidates):
            breakdown = self.scorer.score_detailed(cg)
            bc = BeamCandidate(
                graph=cg,
                score=breakdown.composite_score,
                breakdown=breakdown,
                history=[f"candidate_{idx}"],
            )
            scored.append(bc)

        # Sort by composite score descending
        scored.sort(key=lambda c: c.score, reverse=True)

        # Keep top beam_width
        beam = scored[: self.beam_width]
        rejected = scored[self.beam_width :]

        elapsed_ms = (time.monotonic() - t0) * 1000

        # Build PlanningTrace
        trace = self._build_trace(beam, rejected, elapsed_ms)

        best = beam[0]
        logger.info(
            "Beam search complete: selected candidate_0 with score=%.4f "
            "(beam_width=%d, candidates=%d, time=%.1fms)",
            best.score,
            self.beam_width,
            len(candidates),
            elapsed_ms,
        )

        return best.graph, trace

    def incremental_search(
        self,
        initial_graph: ConstructionGraph,
        expansion_fn,
    ) -> Tuple[ConstructionGraph, Dict[str, Any]]:
        """
        Full incremental beam search.

        At each depth level:
          1. For each beam candidate, call expansion_fn(graph) to get
             possible next operations
          2. Create new candidates by appending each expansion
          3. Score all new candidates
          4. Prune to beam_width

        Args:
            initial_graph: Starting construction graph (may be empty).
            expansion_fn: Callable(ConstructionGraph) -> List[ConstructionNode]
                         Returns possible next operations for a graph.

        Returns:
            Tuple of (best_graph, planning_trace_dict).
        """
        t0 = time.monotonic()

        beam = [BeamCandidate(graph=initial_graph, score=0.0)]
        all_rejected: List[BeamCandidate] = []

        for depth in range(self.max_depth):
            new_candidates: List[BeamCandidate] = []

            for parent in beam:
                expansions = expansion_fn(parent.graph)
                if not expansions:
                    # Terminal state — keep as-is
                    new_candidates.append(parent)
                    continue

                for op in expansions:
                    child = parent.clone()
                    child.graph.add_operation(op)
                    child.history.append(f"d{depth}_{op.operation_type}")

                    bd = self.scorer.score_detailed(child.graph)
                    child.score = bd.composite_score
                    child.breakdown = bd
                    new_candidates.append(child)

            # Sort and prune
            new_candidates.sort(key=lambda c: c.score, reverse=True)
            beam = new_candidates[: self.beam_width]
            all_rejected.extend(new_candidates[self.beam_width :])

            # Early termination: if top candidate hasn't changed
            if depth > 0 and len(beam) == 1:
                break

            logger.debug(
                "Beam search depth=%d: %d candidates, top_score=%.4f",
                depth, len(new_candidates), beam[0].score if beam else 0,
            )

        elapsed_ms = (time.monotonic() - t0) * 1000
        trace = self._build_trace(beam, all_rejected, elapsed_ms)

        best = beam[0] if beam else BeamCandidate(graph=initial_graph)
        return best.graph, trace

    # ------------------------------------------------------------------
    # PlanningTrace builder
    # ------------------------------------------------------------------

    def _build_trace(
        self,
        beam: List[BeamCandidate],
        rejected: List[BeamCandidate],
        elapsed_ms: float,
    ) -> Dict[str, Any]:
        """Build a PlanningTrace dict compatible with shared-schemas."""
        beam_candidates = []
        for idx, bc in enumerate(beam):
            beam_candidates.append({
                "candidate_index": idx,
                "construction_sequence": bc.history,
                "score": round(bc.score, 4),
                "scoring_breakdown": bc.breakdown.to_dict(),
            })

        rejected_plans = []
        for bc in rejected[:10]:  # Cap at 10 for trace readability
            rejected_plans.append({
                "candidate_index": len(beam) + len(rejected_plans),
                "construction_sequence": bc.history,
                "score": round(bc.score, 4),
                "rejection_reason": (
                    f"Score {bc.score:.4f} below beam cutoff "
                    f"{beam[-1].score:.4f}" if beam else "empty beam"
                ),
            })

        return {
            "beam_candidates": beam_candidates,
            "selected_plan_index": 0,
            "rejected_plans": rejected_plans,
            "total_planning_time_ms": round(elapsed_ms, 2),
            "beam_width": self.beam_width,
            "num_candidates_evaluated": len(beam) + len(rejected),
        }
