from typing import List
from construction.graph import ConstructionGraph
from evaluation.scorer import PlanScorer

class BeamSearchPlanner:
    """
    Explores multiple CAD histories generated by the ambiguity resolver.
    """
    
    def __init__(self, beam_width: int = 3):
        self.beam_width = beam_width
        self.scorer = PlanScorer()
        
    def plan(self, candidates: List[ConstructionGraph]) -> ConstructionGraph:
        """
        Evaluates a set of candidate construction graphs and returns the best one.
        For V1, this just scores the candidates and returns the top one.
        A true beam search would incrementally build the graph and prune at each step.
        """
        if not candidates:
            raise ValueError("No candidates provided to Beam Search Planner")
            
        scored_candidates = []
        for cg in candidates:
            score = self.scorer.score(cg)
            scored_candidates.append((score, cg))
            
        # Sort by score descending
        scored_candidates.sort(key=lambda x: x[0], reverse=True)
        
        # Return the best graph
        return scored_candidates[0][1]
